import type { Config } from "tailwindcss";
// eslint-disable-next-line @typescript-eslint/no-var-requires
const sharedTokens = require("./tailwind-tokens.cjs");

// Tokens canonical source: packages/ui/tailwind-tokens.cjs (see scripts/sync-shared.sh).
// This file is regenerated by `bash scripts/sync-shared.sh`. Do not edit directly.
export default {
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  theme: {
    extend: sharedTokens,
  },
  plugins: [],
} satisfies Config;
